version: "3"
services:

  # PHP Service
  cp_app:
    build: .
    container_name: my-articles-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - my-articles-network


  # NGINX Service
  cp_webserver:
    image: nginx:1
    container_name: my-articles-webserver
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - my-articles-network


  # MySQL Service
  cp_db:
    image: mysql:8
    container_name: my-articles-db
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE:  ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD:
    volumes:
      - my-articles-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-articles-network


volumes:
  my-articles-data:

networks:
  my-articles-network:
    driver: bridge
